"""Simple Ruby rules for Bazel."""

def ruby_library(name, srcs = [], deps = [], visibility = None, **kwargs):
    """A simple Ruby library rule.
    
    Args:
        name: Name of the library target
        srcs: List of Ruby source files
        deps: List of dependencies
        visibility: Visibility of the target
        **kwargs: Additional arguments
    """
    native.filegroup(
        name = name,
        srcs = srcs,
        visibility = visibility,
        **kwargs
    )

def ruby_binary(name, srcs = [], main = None, deps = [], data = [], visibility = None, **kwargs):
    """A simple Ruby binary rule.
    
    Args:
        name: Name of the binary target
        srcs: List of Ruby source files
        main: Main Ruby file to execute
        deps: List of dependencies
        data: Additional data files
        visibility: Visibility of the target
        **kwargs: Additional arguments
    """
    main_file = main if main else (srcs[0] if srcs else None)
    
    if not main_file:
        fail("ruby_binary requires either 'main' or at least one file in 'srcs'")
    
    # Create a wrapper script
    wrapper_name = name + "_wrapper.sh"
    wrapper_content = """#!/bin/bash
# Ruby binary wrapper generated by Bazel
RUBY_BIN=$$(which ruby)
SCRIPT_DIR=$$(dirname "$$0")
exec $$RUBY_BIN "$$SCRIPT_DIR/{main}" "$$@"
""".format(main = main_file)
    
    native.genrule(
        name = name + "_wrapper_gen",
        outs = [wrapper_name],
        cmd = "echo '%s' > $@" % wrapper_content,
    )
    
    native.sh_binary(
        name = name,
        srcs = [wrapper_name],
        data = srcs + deps + data,
        visibility = visibility,
        **kwargs
    )

