proto_library(
    name = "litter_usage_metadata_proto",
    srcs = ["litter_usage_metadata.proto"],
    visibility = ["//visibility:public"],
)

# Source filegroup for cases where you need direct proto file access
filegroup(
    name = "litter_usage_metadata_proto_srcs",
    srcs = ["litter_usage_metadata.proto"],
    visibility = ["//visibility:public"],
)
